(* generated by dune *)

(** @canonical Dolmen_intf.Ext *)
module Ext = Dolmen_intf__Ext

(** @canonical Dolmen_intf.Id *)
module Id = Dolmen_intf__Id

(** @canonical Dolmen_intf.Language *)
module Language = Dolmen_intf__Language

(** @canonical Dolmen_intf.Lex *)
module Lex = Dolmen_intf__Lex

(** @canonical Dolmen_intf.Location *)
module Location = Dolmen_intf__Location

(** @canonical Dolmen_intf.Map *)
module Map = Dolmen_intf__Map

(** @canonical Dolmen_intf.Msg *)
module Msg = Dolmen_intf__Msg

(** @canonical Dolmen_intf.Parse *)
module Parse = Dolmen_intf__Parse

(** @canonical Dolmen_intf.Pretty *)
module Pretty = Dolmen_intf__Pretty

(** @canonical Dolmen_intf.Stmt *)
module Stmt = Dolmen_intf__Stmt

(** @canonical Dolmen_intf.Tag *)
module Tag = Dolmen_intf__Tag

(** @canonical Dolmen_intf.Term *)
module Term = Dolmen_intf__Term

(** @canonical Dolmen_intf.Tok *)
module Tok = Dolmen_intf__Tok

(** @canonical Dolmen_intf.Ty *)
module Ty = Dolmen_intf__Ty
