(* generated by dune *)

(** @canonical Dolmen_dimacs.Ast *)
module Ast = Dolmen_dimacs__Ast

(** @canonical Dolmen_dimacs.Lexer *)
module Lexer = Dolmen_dimacs__Lexer

(** @canonical Dolmen_dimacs.Parser *)
module Parser = Dolmen_dimacs__Parser

(** @canonical Dolmen_dimacs.Syntax_messages *)
module Syntax_messages = Dolmen_dimacs__Syntax_messages

(** @canonical Dolmen_dimacs.Tokens *)
module Tokens = Dolmen_dimacs__Tokens
