(* generated by dune *)

(** @canonical EslBase.Base *)
module Base = EslBase__Base

(** @canonical EslBase.Cont *)
module Cont = EslBase__Cont

(** @canonical EslBase.Font *)
module Font = EslBase__Font

(** @canonical EslBase.Io *)
module Io = EslBase__Io

(** @canonical EslBase.Log *)
module Log = EslBase__Log

(** @canonical EslBase.String *)
module String = EslBase__String

(** @canonical EslBase.Terminal *)
module Terminal = EslBase__Terminal
