(* generated by dune *)

(** @canonical Ocaml_intrinsics.Atomic *)
module Atomic = Ocaml_intrinsics__Atomic

(** @canonical Ocaml_intrinsics.Atomic_expert *)
module Atomic_expert = Ocaml_intrinsics__Atomic_expert

(** @canonical Ocaml_intrinsics.Bigstring_intf *)
module Bigstring_intf = Ocaml_intrinsics__Bigstring_intf

(** @canonical Ocaml_intrinsics.Conditional *)
module Conditional = Ocaml_intrinsics__Conditional

(** @canonical Ocaml_intrinsics.Crc *)
module Crc = Ocaml_intrinsics__Crc

(** @canonical Ocaml_intrinsics.Ext_pointer *)
module Ext_pointer = Ocaml_intrinsics__Ext_pointer

(** @canonical Ocaml_intrinsics.Fences *)
module Fences = Ocaml_intrinsics__Fences

(** @canonical Ocaml_intrinsics.Float *)
module Float = Ocaml_intrinsics__Float

(** @canonical Ocaml_intrinsics.Int *)
module Int = Ocaml_intrinsics__Int

(** @canonical Ocaml_intrinsics.Int32 *)
module Int32 = Ocaml_intrinsics__Int32

(** @canonical Ocaml_intrinsics.Int64 *)
module Int64 = Ocaml_intrinsics__Int64

(** @canonical Ocaml_intrinsics.Native_pointer *)
module Native_pointer = Ocaml_intrinsics__Native_pointer

(** @canonical Ocaml_intrinsics.Nativeint *)
module Nativeint = Ocaml_intrinsics__Nativeint

(** @canonical Ocaml_intrinsics.Perfmon *)
module Perfmon = Ocaml_intrinsics__Perfmon

(** @canonical Ocaml_intrinsics.Prefetch *)
module Prefetch = Ocaml_intrinsics__Prefetch

(** @canonical Ocaml_intrinsics.Prefetch_expert *)
module Prefetch_expert = Ocaml_intrinsics__Prefetch_expert
