(* generated by dune *)

(** @canonical Dolmen_std.Answer *)
module Answer = Dolmen_std__Answer

(** @canonical Dolmen_std.Builtin *)
module Builtin = Dolmen_std__Builtin

(** @canonical Dolmen_std.Escape *)
module Escape = Dolmen_std__Escape

(** @canonical Dolmen_std.Expr *)
module Expr = Dolmen_std__Expr

(** @canonical Dolmen_std.Extensions *)
module Extensions = Dolmen_std__Extensions

(** @canonical Dolmen_std.Id *)
module Id = Dolmen_std__Id

(** @canonical Dolmen_std.Loc *)
module Loc = Dolmen_std__Loc

(** @canonical Dolmen_std.Maps *)
module Maps = Dolmen_std__Maps

(** @canonical Dolmen_std.Maps_string *)
module Maps_string = Dolmen_std__Maps_string

(** @canonical Dolmen_std.Misc *)
module Misc = Dolmen_std__Misc

(** @canonical Dolmen_std.Msg *)
module Msg = Dolmen_std__Msg

(** @canonical Dolmen_std.Name *)
module Name = Dolmen_std__Name

(** @canonical Dolmen_std.Namespace *)
module Namespace = Dolmen_std__Namespace

(** @canonical Dolmen_std.Normalize *)
module Normalize = Dolmen_std__Normalize

(** @canonical Dolmen_std.Path *)
module Path = Dolmen_std__Path

(** @canonical Dolmen_std.Pretty *)
module Pretty = Dolmen_std__Pretty

(** @canonical Dolmen_std.Statement *)
module Statement = Dolmen_std__Statement

(** @canonical Dolmen_std.Stats *)
module Stats = Dolmen_std__Stats

(** @canonical Dolmen_std.Tag *)
module Tag = Dolmen_std__Tag

(** @canonical Dolmen_std.Term *)
module Term = Dolmen_std__Term

(** @canonical Dolmen_std.Timer *)
module Timer = Dolmen_std__Timer

(** @canonical Dolmen_std.Tok *)
module Tok = Dolmen_std__Tok

(** @canonical Dolmen_std.Transformer *)
module Transformer = Dolmen_std__Transformer

(** @canonical Dolmen_std.Vec *)
module Vec = Dolmen_std__Vec
