(* generated by dune *)

(** @canonical Dolmen_tptp_v6_3_0.Ast *)
module Ast = Dolmen_tptp_v6_3_0__Ast

(** @canonical Dolmen_tptp_v6_3_0.Lexer *)
module Lexer = Dolmen_tptp_v6_3_0__Lexer

(** @canonical Dolmen_tptp_v6_3_0.Parser *)
module Parser = Dolmen_tptp_v6_3_0__Parser

(** @canonical Dolmen_tptp_v6_3_0.Syntax_messages *)
module Syntax_messages = Dolmen_tptp_v6_3_0__Syntax_messages

(** @canonical Dolmen_tptp_v6_3_0.Tokens *)
module Tokens = Dolmen_tptp_v6_3_0__Tokens
