(* generated by dune *)

(** @canonical Farith.Assert *)
module Assert = Farith__Assert

(** @canonical Farith.BinInt *)
module BinInt = Farith__BinInt

(** @canonical Farith.BinNums *)
module BinNums = Farith__BinNums

(** @canonical Farith.BinPos *)
module BinPos = Farith__BinPos

(** @canonical Farith.BinPosDef *)
module BinPosDef = Farith__BinPosDef

(** @canonical Farith.Binary *)
module Binary = Farith__Binary

(** @canonical Farith.BinarySingleNaN *)
module BinarySingleNaN = Farith__BinarySingleNaN

(** @canonical Farith.Bits *)
module Bits = Farith__Bits

(** @canonical Farith.Bool *)
module Bool = Farith__Bool

(** @canonical Farith.Datatypes *)
module Datatypes = Farith__Datatypes

(** @canonical Farith.Defs *)
module Defs = Farith__Defs

(** @canonical Farith.Farith_Big *)
module Farith_Big = Farith__Farith_Big

(** @canonical Farith.FloatClass *)
module FloatClass = Farith__FloatClass

(** @canonical Farith.GenericFloat *)
module GenericFloat = Farith__GenericFloat

(** @canonical Farith.Interval *)
module Interval = Farith__Interval

(** @canonical Farith.Op *)
module Op = Farith__Op

(** @canonical Farith.Operations *)
module Operations = Farith__Operations

(** @canonical Farith.Qextended *)
module Qextended = Farith__Qextended

(** @canonical Farith.Round *)
module Round = Farith__Round

(** @canonical Farith.SpecFloat *)
module SpecFloat = Farith__SpecFloat

(** @canonical Farith.Specif *)
module Specif = Farith__Specif

(** @canonical Farith.Utils *)
module Utils = Farith__Utils

(** @canonical Farith.Version *)
module Version = Farith__Version

(** @canonical Farith.Zaux *)
module Zaux = Farith__Zaux

(** @canonical Farith.Zbool *)
module Zbool = Farith__Zbool

(** @canonical Farith.Zpower *)
module Zpower = Farith__Zpower
