(* generated by dune *)

(** @canonical Dolmen_model.Adt *)
module Adt = Dolmen_model__Adt

(** @canonical Dolmen_model.Array *)
module Array = Dolmen_model__Array

(** @canonical Dolmen_model.Bitv *)
module Bitv = Dolmen_model__Bitv

(** @canonical Dolmen_model.Bool *)
module Bool = Dolmen_model__Bool

(** @canonical Dolmen_model.Coercion *)
module Coercion = Dolmen_model__Coercion

(** @canonical Dolmen_model.Core *)
module Core = Dolmen_model__Core

(** @canonical Dolmen_model.Env *)
module Env = Dolmen_model__Env

(** @canonical Dolmen_model.Eval *)
module Eval = Dolmen_model__Eval

(** @canonical Dolmen_model.Fp *)
module Fp = Dolmen_model__Fp

(** @canonical Dolmen_model.Fun *)
module Fun = Dolmen_model__Fun

(** @canonical Dolmen_model.Int *)
module Int = Dolmen_model__Int

(** @canonical Dolmen_model.Loop *)
module Loop = Dolmen_model__Loop

(** @canonical Dolmen_model.Model *)
module Model = Dolmen_model__Model

(** @canonical Dolmen_model.Rat *)
module Rat = Dolmen_model__Rat

(** @canonical Dolmen_model.Real *)
module Real = Dolmen_model__Real

(** @canonical Dolmen_model.Value *)
module Value = Dolmen_model__Value
