opam-version: "2.0"
lib: [
  "_build/install/default/lib/scfg/.private/scfg__Lexer.cmi"
    {".private/scfg__Lexer.cmi"}
  "_build/install/default/lib/scfg/.private/scfg__Lexer.cmt"
    {".private/scfg__Lexer.cmt"}
  "_build/install/default/lib/scfg/.private/scfg__Menhir_parser.cmi"
    {".private/scfg__Menhir_parser.cmi"}
  "_build/install/default/lib/scfg/.private/scfg__Menhir_parser.cmt"
    {".private/scfg__Menhir_parser.cmt"}
  "_build/install/default/lib/scfg/.private/scfg__Menhir_parser.cmti"
    {".private/scfg__Menhir_parser.cmti"}
  "_destdir/home/arckenimuz/dev/ECMA-SL/_opam/lib/scfg/META"
  "_destdir/home/arckenimuz/dev/ECMA-SL/_opam/lib/scfg/dune-package"
  "_build/install/default/lib/scfg/lexer.ml"
  "_build/install/default/lib/scfg/menhir_parser.ml"
  "_build/install/default/lib/scfg/menhir_parser.mli"
  "_build/install/default/lib/scfg/opam"
  "_build/install/default/lib/scfg/parse.ml"
  "_build/install/default/lib/scfg/pp.ml"
  "_build/install/default/lib/scfg/query.ml"
  "_build/install/default/lib/scfg/scfg.a"
  "_build/install/default/lib/scfg/scfg.cma"
  "_build/install/default/lib/scfg/scfg.cmi"
  "_build/install/default/lib/scfg/scfg.cmt"
  "_build/install/default/lib/scfg/scfg.cmx"
  "_build/install/default/lib/scfg/scfg.cmxa"
  "_build/install/default/lib/scfg/scfg.ml"
  "_build/install/default/lib/scfg/scfg__Lexer.cmx"
  "_build/install/default/lib/scfg/scfg__Menhir_parser.cmx"
  "_build/install/default/lib/scfg/scfg__Parse.cmi"
  "_build/install/default/lib/scfg/scfg__Parse.cmt"
  "_build/install/default/lib/scfg/scfg__Parse.cmx"
  "_build/install/default/lib/scfg/scfg__Pp.cmi"
  "_build/install/default/lib/scfg/scfg__Pp.cmt"
  "_build/install/default/lib/scfg/scfg__Pp.cmx"
  "_build/install/default/lib/scfg/scfg__Query.cmi"
  "_build/install/default/lib/scfg/scfg__Query.cmt"
  "_build/install/default/lib/scfg/scfg__Query.cmx"
  "_build/install/default/lib/scfg/scfg__Types.cmi"
  "_build/install/default/lib/scfg/scfg__Types.cmt"
  "_build/install/default/lib/scfg/scfg__Types.cmx"
  "_build/install/default/lib/scfg/types.ml"
]
bin: "_build/install/default/bin/scfg"
doc: [
  "_build/install/default/doc/scfg/CHANGES.md"
  "_build/install/default/doc/scfg/LICENSE.md"
  "_build/install/default/doc/scfg/README.md"
  "_build/install/default/doc/scfg/odoc-pages/index.mld"
    {"odoc-pages/index.mld"}
]
libexec: "_build/install/default/lib/scfg/scfg.cmxs"
