(* generated by dune *)

(** @canonical Dolmen_ae.Ast *)
module Ast = Dolmen_ae__Ast

(** @canonical Dolmen_ae.Lexer *)
module Lexer = Dolmen_ae__Lexer

(** @canonical Dolmen_ae.Parser *)
module Parser = Dolmen_ae__Parser

(** @canonical Dolmen_ae.Syntax_messages *)
module Syntax_messages = Dolmen_ae__Syntax_messages

(** @canonical Dolmen_ae.Tokens *)
module Tokens = Dolmen_ae__Tokens
