(* generated by dune *)

(** @canonical Dolmen_icnf.Ast *)
module Ast = Dolmen_icnf__Ast

(** @canonical Dolmen_icnf.Lexer *)
module Lexer = Dolmen_icnf__Lexer

(** @canonical Dolmen_icnf.Parser *)
module Parser = Dolmen_icnf__Parser

(** @canonical Dolmen_icnf.Syntax_messages *)
module Syntax_messages = Dolmen_icnf__Syntax_messages

(** @canonical Dolmen_icnf.Tokens *)
module Tokens = Dolmen_icnf__Tokens
