(* generated by dune *)

(** @canonical Dolmen_zf.Ast *)
module Ast = Dolmen_zf__Ast

(** @canonical Dolmen_zf.Lexer *)
module Lexer = Dolmen_zf__Lexer

(** @canonical Dolmen_zf.Parser *)
module Parser = Dolmen_zf__Parser

(** @canonical Dolmen_zf.Syntax_messages *)
module Syntax_messages = Dolmen_zf__Syntax_messages

(** @canonical Dolmen_zf.Tokens *)
module Tokens = Dolmen_zf__Tokens
