(* generated by dune *)

(** @canonical EslSyntax.EAdvice *)
module EAdvice = EslSyntax__EAdvice

(** @canonical EslSyntax.EExpr *)
module EExpr = EslSyntax__EExpr

(** @canonical EslSyntax.EFunc *)
module EFunc = EslSyntax__EFunc

(** @canonical EslSyntax.EImport *)
module EImport = EslSyntax__EImport

(** @canonical EslSyntax.EMacro *)
module EMacro = EslSyntax__EMacro

(** @canonical EslSyntax.EPat *)
module EPat = EslSyntax__EPat

(** @canonical EslSyntax.EProg *)
module EProg = EslSyntax__EProg

(** @canonical EslSyntax.EStmt *)
module EStmt = EslSyntax__EStmt

(** @canonical EslSyntax.EType *)
module EType = EslSyntax__EType

(** @canonical EslSyntax.Expr *)
module Expr = EslSyntax__Expr

(** @canonical EslSyntax.Func *)
module Func = EslSyntax__Func

(** @canonical EslSyntax.Id *)
module Id = EslSyntax__Id

(** @canonical EslSyntax.Loc *)
module Loc = EslSyntax__Loc

(** @canonical EslSyntax.Object *)
module Object = EslSyntax__Object

(** @canonical EslSyntax.Operator *)
module Operator = EslSyntax__Operator

(** @canonical EslSyntax.Prog *)
module Prog = EslSyntax__Prog

(** @canonical EslSyntax.Source *)
module Source = EslSyntax__Source

(** @canonical EslSyntax.Stmt *)
module Stmt = EslSyntax__Stmt

(** @canonical EslSyntax.Value *)
module Value = EslSyntax__Value
