(* generated by dune *)

(** @canonical Scfg.Lexer *)
module Lexer = Scfg__Lexer

(** @canonical Scfg.Menhir_parser *)
module Menhir_parser = Scfg__Menhir_parser

(** @canonical Scfg.Parse *)
module Parse = Scfg__Parse

(** @canonical Scfg.Pp *)
module Pp = Scfg__Pp

(** @canonical Scfg.Query *)
module Query = Scfg__Query

(** @canonical Scfg.Types *)
module Types = Scfg__Types
