(* generated by dune *)

(** @canonical PatriciaTree.Functors *)
module Functors = PatriciaTree__Functors

(** @canonical PatriciaTree.Ints *)
module Ints = PatriciaTree__Ints

(** @canonical PatriciaTree.Key_value *)
module Key_value = PatriciaTree__Key_value

(** @canonical PatriciaTree.Nodes *)
module Nodes = PatriciaTree__Nodes

(** @canonical PatriciaTree.Signatures *)
module Signatures = PatriciaTree__Signatures
