(* generated by dune *)

(** @canonical Mdx.Block *)
module Block = Mdx__Block

(** @canonical Mdx.Compat *)
module Compat = Mdx__Compat

(** @canonical Mdx.Cram *)
module Cram = Mdx__Cram

(** @canonical Mdx.Dep *)
module Dep = Mdx__Dep

(** @canonical Mdx.Deprecated *)
module Deprecated = Mdx__Deprecated

(** @canonical Mdx.Document *)
module Document = Mdx__Document

(** @canonical Mdx.Label *)
module Label = Mdx__Label

(** @canonical Mdx.Lexer_cram *)
module Lexer_cram = Mdx__Lexer_cram

(** @canonical Mdx.Lexer_mdx *)
module Lexer_mdx = Mdx__Lexer_mdx

(** @canonical Mdx.Lexer_top *)
module Lexer_top = Mdx__Lexer_top

(** @canonical Mdx.Library *)
module Library = Mdx__Library

(** @canonical Mdx.Misc *)
module Misc = Mdx__Misc

(** @canonical Mdx.Mli_parser *)
module Mli_parser = Mdx__Mli_parser

(** @canonical Mdx.Ocaml_env *)
module Ocaml_env = Mdx__Ocaml_env

(** @canonical Mdx.Output *)
module Output = Mdx__Output

(** @canonical Mdx.Part *)
module Part = Mdx__Part

(** @canonical Mdx.Pp *)
module Pp = Mdx__Pp

(** @canonical Mdx.Prelude *)
module Prelude = Mdx__Prelude

(** @canonical Mdx.Stable_printer *)
module Stable_printer = Mdx__Stable_printer

(** @canonical Mdx.Syntax *)
module Syntax = Mdx__Syntax

(** @canonical Mdx.Toplevel *)
module Toplevel = Mdx__Toplevel

(** @canonical Mdx.Util *)
module Util = Mdx__Util

module Mdx__ = struct end
[@@deprecated "this module is shadowed"]
