(* generated by dune *)

(** @canonical Dolmen_type.Arith *)
module Arith = Dolmen_type__Arith

(** @canonical Dolmen_type.Arrays *)
module Arrays = Dolmen_type__Arrays

(** @canonical Dolmen_type.Base *)
module Base = Dolmen_type__Base

(** @canonical Dolmen_type.Bitv *)
module Bitv = Dolmen_type__Bitv

(** @canonical Dolmen_type.Core *)
module Core = Dolmen_type__Core

(** @canonical Dolmen_type.Def *)
module Def = Dolmen_type__Def

(** @canonical Dolmen_type.Float *)
module Float = Dolmen_type__Float

(** @canonical Dolmen_type.Intf *)
module Intf = Dolmen_type__Intf

(** @canonical Dolmen_type.Logic *)
module Logic = Dolmen_type__Logic

(** @canonical Dolmen_type.Misc *)
module Misc = Dolmen_type__Misc

(** @canonical Dolmen_type.Strings *)
module Strings = Dolmen_type__Strings

(** @canonical Dolmen_type.Tff *)
module Tff = Dolmen_type__Tff

(** @canonical Dolmen_type.Tff_intf *)
module Tff_intf = Dolmen_type__Tff_intf

(** @canonical Dolmen_type.Thf *)
module Thf = Dolmen_type__Thf

(** @canonical Dolmen_type.Thf_intf *)
module Thf_intf = Dolmen_type__Thf_intf
